# Every new field must be added to /buildSrc/src/main/groovy/multiloader-common.gradle

# Project
group=com.khazoda.basicweapons
version=2.3.0
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]

# Mod-List Details
mod_name=Basic Weapons
mod_author=Khazoda
mod_id=basicweapons
mod_homepage=https://www.khazoda.com#basicweapons
mod_issues=https://github.com/Khazoda/basicweapons/issues
description=Adds basic vanilla+ weaponry
license=GPLv3
credits=

# NeoForm https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# Parchment https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric https://fabricmc.net/develop/
fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2
fabric_loader_version_minimum=0.18.0

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.4-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Java
java_version=21

