@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khazoda.basicweapons.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;