@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khazoda.basicweapons.material;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;