@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khazoda.basicweapons.material;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;