@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khazoda.basicweapons.materialpack;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;